### ISSUE TITLE
Impossible de trouver la fonction "tile.url.stamenwaterbw"

### ISSUE THREAD

**Issue by moreymat** [joelgombin/frontieres-invisibles#1]
Quand j'essaie d'exécuter `limites.R`, l'erreur suivante se produit:

``` R
> MarseilleOSM <- getTiles(IRISMarseille, type = "stamenwaterbw", crop = TRUE)
Zoom: 11
Error in do.call(paste0("tile.url.", type), list(xtile, ytile, zoom)) : 
  impossible de trouver la fonction "tile.url.stamenwaterbw"
```

Je n'arrive pas à retrouver de définition du type de carte `stamenwaterbw` (ROSM connaît `stamenbw` et `stamenwatercolor`).

**Comment by joelgombin** [comment]
D'abord, je suis content de savoir que quelqu'un utilise effectivement le code de mes chroniques ;-)

Ensuite, il y a effectivement une erreur, c'est bien "stamenwatercolor".

Enfin, le code le plus récent (mis en prod sur Marsactu) est celui de la branche `leaflet` (https://github.com/joelgombin/frontieres-invisibles/tree/leaflet).

**Comment by moreymat** [comment]
Super!
Au passage, la branche `leaflet`est également touchée par ce bug.

**Comment by joelgombin** [comment]
Sauf qu'en fait `limites.R` ne devrait même pas figurer sur la branche
leaflet, il faut utiliser `limites.Rmd` ou (pour produire chaque carte
séparément, ce qui a finalement été fait par Marsactu) `cartes.R`.

On Thu, Apr 14, 2016 at 10:12 AM, Mathieu Morey notifications@github.com
wrote:

> Super!
> Au passage, la branche leafletest également touchée par ce bug.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/joelgombin/frontieres-invisibles/issues/1#issuecomment-209820730

## 

Joël Gombin

Doctorant en science politique / PhD candidate in political science
CURAPP - Université de Picardie Jules Verne

Parc Bella Vista, bâtiment D
11, allée Sacoman
13016 Marseille

Tel : +33 (0)6 61 55 22 41
www.joelgombin.fr

**Comment by moreymat** [comment]
Arg, je me suis fait avoir comme un bleu.

Merci pour le bugfix et merci pour la chronique.
